// flow-typed signature: f3b42cfab1798b84a52395e169146a37
// flow-typed version: <<STUB>>/boxen-notify_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boxen-notify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boxen-notify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'boxen-notify/index' {
  declare module.exports: $Exports<'boxen-notify'>;
}
declare module 'boxen-notify/index.js' {
  declare module.exports: $Exports<'boxen-notify'>;
}
