// flow-typed signature: bca4ee7329496a6cfd87afe7452e2bf0
// flow-typed version: <<STUB>>/is-npm_v^1.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-npm/index' {
  declare module.exports: $Exports<'is-npm'>;
}
declare module 'is-npm/index.js' {
  declare module.exports: $Exports<'is-npm'>;
}
